# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: main:Build:All:Deploy:Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.17.0'

      - name: build enigma-full
        working-directory: ./Enigma/Full
        run: |
          npm install
          npm run build:azure
          
      - name: build enigma-starter
        working-directory: ./Enigma/Starter
        run: |
          npm install
          npm run build:azure
          
      - name: build icewall-full
        working-directory: ./Icewall/Full
        run: |
          npm install
          npm run build:azure
          
      - name: build icewall-starter
        working-directory: ./Icewall/Starter
        run: |
          npm install
          npm run build:azure
      
      - name: build tinker-full
        working-directory: ./Tinker/Full
        run: |
          npm install
          npm run build:azure
          
      - name: build tinker-starter
        working-directory: ./Tinker/Starter
        run: |
          npm install
          npm run build:azure
          
      - name: build rubic-full
        working-directory: ./Rubic/Full
        run: |
          npm install
          npm run build:azure
          
      - name: build rubic-starter
        working-directory: ./Rubic/Starter
        run: |
          npm install
          npm run build:azure
    
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'midone-vue3-template-fs'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_490853AEF1554CAB9CF78A3458595C64 }}
          package: ./Releases/
